### ISSUE TITLE
Null reference exceptions in play mode when Experimental Play Mode options are enabled.

### ISSUE THREAD

**Issue by rurre** [BlackStartx/VRC-Gesture-Manager#10]
Seems like the gesture manager only works once successfully. 
After leaving playmode once and going back in I'm spammed with null reference exceptions.

```
MissingReferenceException: The object of type 'AnimationClip' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.Object.get_name () (at <7d87237cea3743d093e22c5b98f74fba>:0)
GestureManager.Scripts.Editor.GestureManagerEditor.OnCheckBoxGuiHandAnimation (GestureManager.Scripts.Extra.ModuleBase module, System.Int32 i, System.Int32 position, System.Boolean overrider, System.Boolean& isOn) (at Assets/GestureManager/Scripts/Editor/GestureManagerEditor.cs:213)
GestureManager.Scripts.Editor.GestureManagerEditor.OnCheckBoxGuiHand (GestureManager.Scripts.Extra.ModuleBase module, GestureManager.Scripts.Extra.GestureHand hand, System.Int32 position, System.Boolean overrider) (at Assets/GestureManager/Scripts/Editor/GestureManagerEditor.cs:207)
GestureManager.Scripts.Editor.Modules.Vrc3.ModuleVrc3.EditorContentGesture (UnityEngine.UIElements.VisualElement element, GestureManager.Scripts.Editor.Modules.Vrc3.Vrc3WeightController weightController) (at Assets/GestureManager/Scripts/Editor/Modules/Vrc3/ModuleVrc3.cs:276)
GestureManager.Scripts.Editor.Modules.Vrc3.ModuleVrc3+<>c__DisplayClass44_0.<EditorContent>b__0 () (at Assets/GestureManager/Scripts/Editor/Modules/Vrc3/ModuleVrc3.cs:210)
GestureManager.Scripts.Core.Editor.GmgLayoutHelper.MyToolbar (System.Int32& toolbar, UnityEngine.GUIContent[] contents, System.ValueTuple`2[System.String,System.Action][] actions) (at Assets/GestureManager/Scripts/Core/Editor/GmgLayoutHelper.cs:40)
GestureManager.Scripts.Core.Editor.GmgLayoutHelper.MyToolbar (GestureManager.Scripts.Core.Editor.GmgLayoutHelper+Toolbar& toolbar, System.ValueTuple`2[System.String,System.Action][] field) (at Assets/GestureManager/Scripts/Core/Editor/GmgLayoutHelper.cs:35)
GestureManager.Scripts.Editor.Modules.Vrc3.ModuleVrc3.EditorContent (System.Object editor, UnityEngine.UIElements.VisualElement element) (at Assets/GestureManager/Scripts/Editor/Modules/Vrc3/ModuleVrc3.cs:208)
GestureManager.Scripts.Editor.GestureManagerEditor.ManagerGui () (at Assets/GestureManager/Scripts/Editor/GestureManagerEditor.cs:95)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.DoIMGUIRepaint () (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.UIR.RenderChainCommand.ExecuteNonDrawMesh (UnityEngine.UIElements.UIR.DrawParams drawParams, System.Boolean straightY, System.Single pixelsPerPoint, System.Exception& immediateException) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
Rethrow as ImmediateModeException
UnityEngine.UIElements.UIR.RenderChain.Render (UnityEngine.Rect viewport, UnityEngine.Matrix4x4 projection, UnityEngine.UIElements.PanelClearFlags clearFlags) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
```

Looking into it, it seems that the ModuleVrc3Styles.Data.GestureClips array is full of null AnimationClips and the code is trying to grab the name of them.

Nothing unusual about my setup, I'd think. I only have 1 scene loaded with one avatar. Just looks like unity is destroying the animation clips.

Using VRCSDK3-AVATAR-2022.06.03.00.04 and Unity 2019.4.31f.

**Comment by BlackStartx** [comment]
Hi Rurre~
First of all, sorry for the issue :c

Sadly I am unable to replicate it and have no clue why Unity is destroying those clips in the array.
###### (It may be some strange Unity memory cleaning process... even if the variable are still referenced?)
<br>

But I can say that the portion of code causing this issue was desinged way back in time while I was developing a lot of feature at once and I can say it need a revamp since that array is completely pointless~ ^-^'
(It's been designed this way for backward compatibility with SDK 2.0)

Right now, if you want to fix it manually and fast I would suggest to change the line from: 
`GUILayout.Label(module.GetFinalGestureByIndex(i).name);`
To:
`GUILayout.Label(GestureManagerStyles.Data.GestureNames[i]);`

at Assets/GestureManager/Scripts/Editor/GestureManagerEditor.cs:214

This will not be the final fix, but it will do the trick for now~ :3
I would probably rearrange the code to return just the string rather than the UnityEngine.Object in a future version. ^-^

Thanks and sorry once again~ ♥

**Comment by rurre** [comment]
Hey, thanks for the resposne. I didn't realize I forgot to resepond to this.

I did the changes locally and everything works well! Thank you!

**Comment by rurre** [comment]
I think I've actually figured out why the null refs happen!

If you enable `Project Settings > Editor > Enter Play Mode Options (Experimental)` (at the bottom). 
Using this option makes entering playmode a lot lot faster but it seems to kill the references.

**Comment by BlackStartx** [comment]
Uhhh, this is interesting, thanks for finding it out, Rurre~ * ^ *

I had another user experience the same issue and I wanted to dig further in to this problem to understand the cause~
Now that you pointed this out I also tried myself and can confirm that entering Play-Mode with Reload Domain unticket unload some core data of my tool after leaving Play-Mode for the first time.

Not only the Animation Clips are lost, but also the Avatar Masks of the Playable Layers... causing simulation issues.

I'll refractor my code to prevent problems with those settings and probably release a 3.7 with the issue fixed~

Thanks again~ ♥

**Comment by rurre** [comment]
Great!
