### ISSUE TITLE
isLocal parameter support?

### ISSUE THREAD

**Issue by Kieaer** [BlackStartx/VRC-Gesture-Manager#14]
When using the isLocal parameter like VRCLens, i need a feature that can test the feature that is visible only to myself.

**Comment by BlackStartx** [comment]
Hi Kieaer~

Currently the isLocal parameter can only be changed once the simulation is started, which may lead to some inconsistency between the simulation and a real-case scenario where that value is initialized before booting the simulation.

I'll definetly add a feature that allow the user to set the initial values of default parameters before starting the simulation~

Meanwhile you may try to toggle the parameter at runtime either by using the button in the `Option -> Extra` tab of the RadialMenu or by using the Debug panel~ ^-^

Sorry for the issue~ ;w;

**Comment by BlackStartx** [comment]
Hi Kieaer~ 🌺

It's been 3 months and I'm so sorry for this issue, but good news are coming! :3

I drastically changed the way parameters are initialized and (temporarely) made the IsLocal parameter saved between avatar resets!

This way you can turn off the IsLocal parameter and reset your avatar via the Expression menu to test exactly how your avatar would behave for remote players and viceversa!

I'll share here a preview package:

[Gesture Manager 3.8.3-rc1.zip](https://github.com/BlackStartx/VRC-Gesture-Manager/files/10670673/GestureManager3.8.3-rc1.zip)

Feel free to tell if this solution solves the problem, I will keep this issue open until the feature is implemented in main branch!

Thanks once again and sorry so much for the delay! :c ♥

###### P.S: Parameter initialisation was also bugged and inconsistent, that's not an issue anymore!

**Comment by BlackStartx** [comment]
Hi Kiaer~ 🌺

I've finally implemented this in an official way, with a toggle in the new Gesture Manager's settings tab~

![image](https://github.com/BlackStartx/VRC-Gesture-Manager/assets/26898122/91f15a14-4976-474e-bdbd-44adc0cc1aca)

I think this is the best way to allow the user to choose the initial state of the value~ ^-^

I'll close this issue once the version will be approved in the VCC application! ♥

Sorry for the delay~
- BlackStartx

**Comment by Kieaer** [comment]
Thanks!
