### ISSUE TITLE
missing script

### ISSUE THREAD

**Issue by Deathboy671** [BlackStartx/VRC-Gesture-Manager#16]
Not sure what im missing Packages\dev.vrlabs.av3manager\Editor\Elements\ClipsSwapAreaElement.cs(15,22): error CS0246: The type or namespace name 'ClipSwapItem' could not be found (are you missing a using directive or an assembly reference?)

**Comment by Deathboy671** [comment]
fixed it gesture manager and avatar manager were conflicting with each other

**Comment by BlackStartx** [comment]
Good!

Glad the issue is gone~ ^-^ ♥
