### ISSUE TITLE
[Request] "Performance Test" Tool 

### ISSUE THREAD

**Issue by ZenithVal** [BlackStartx/VRC-Gesture-Manager#17]
Tupper recommended using Gesture Manager as a tool to gauge how performant our avatar animators are. [link](https://twitter.com/dtupper/status/1622663494524080128)

By referencing the Animator.Update time in the unity profiler we can get a performance stat for our animators. Even if it's not a perfect emulation of how the animator is at runtime in VRC, it's an alright ballpark number. 

It'd be nice if there was a  button within the tools section that initiates an animator test/benchmark. It could start the unity profiler, collect Animator.Update times, and display the current & average as it continues. A non-technical user would never open the profiler and examine their animator so if this was built right into the tool section of Gesture manager, it could open eyes for many as to why animator optimization is important.

Edit: Clarity

**Comment by BlackStartx** [comment]
Hey Zenith~ :3 ✨ 

I've implemented this in the new 3.8.5 version, here is a sneak peek!

![image](https://github.com/BlackStartx/VRC-Gesture-Manager/assets/26898122/45b2a559-a37e-4acd-8d2d-9cc11d424a53)

I found it interesting as well, so I'm glad I'm able to add it to the tool! 🌺 

Oh, and it's also **modular**! 
So it can be edited to aim at different records easily. (only form code)

Hope you like it~
- BlackStartx

**Comment by jellejurre** [comment]
Hi BlackStartX

Please note that Animator.Update isn't the only place where animator performance increases.

In my testing I noticed that adding PreLateUpdate.DirectorUpdateAnimationBegin and PreLateUpdate.DirectorUpdateAnimationEnd give you the most accurate representations.

![image](https://github.com/BlackStartx/VRC-Gesture-Manager/assets/76777936/fd4d07f7-178e-424e-8b86-3ad064a853ca)

Above you can see the performance of a scene with 920 layers with 2 state toggles and nothing else, and you can see that AnimatorControllerPlayable.PrepareFrame also takes up quite some time, as an example. This would be missed by using just Animator.Update
