### ISSUE TITLE
Gesture manager does not work normally.

### ISSUE THREAD

**Issue by Ryeoha** [BlackStartx/VRC-Gesture-Manager#20]
Dear BlackStartx,
Hello. While testing the animation using Gesture Manager, I found something strange.
After creating a new animation, setting the menu and FX, etc., I ran Toogle as a gesture manager, but the animations that worked normally before did not work.
In the debug window, it can be confirmed that the value is changed normally.
However, in VRChat in-game, all animations work normally.

Do you know anything about this phenomenon?

Best Regards,
Ryeoha Yoon.

**Comment by BlackStartx** [comment]
Hi Ryeoha~ 🌺 
Sorry for the late reply~ ;^;

By the way, are you still experiencing this?
I don't quite get whats going on since it sounds a lot generic~

It's currently hard for me to replicate it and analyze this issue... 👉🏻👈🏻
