### ISSUE TITLE
A few of the issues I have noticed.

### ISSUE THREAD

**Issue by MistressPlague** [BlackStartx/VRC-Gesture-Manager#23]
1. Lack of a option to apply saved params config from VRC to avatar.
2. OSC system does not apply all parameters correctly. Only built in ones it seems. All of my long param named params fail to apply, but show in the Receive region. Unsure if it is related to my param names being long, or a actual bug.

**Comment by MistressPlague** [comment]
![image](https://github.com/BlackStartx/VRC-Gesture-Manager/assets/36628963/854fd3f6-3618-4e50-a4b9-25a2dede8f54)

**Comment by MistressPlague** [comment]
3. GestureManager OSC fails to get values of saved only parameters. This could be a VRC level OSC issue, though. The antirip I am developing has parameters that are not in the radial menu, but are saved regardless via code. This fails to be sent/found in OSC.

**Comment by MistressPlague** [comment]
Ability to apply avatar config to avatar params via gesturemanager would make all of these issues mute it seems, minus 2. 2 would still be worth fixing.

**Comment by BlackStartx** [comment]
Hi Pleague~ :3 ✨ 

- Point 1

Are you talking about a way to load the values that are saved by the client and stored in the VRChat folder?

That would be cool indeed, the only reason that has stopped me to developing it is that I would need the userID to find the correct path for the file inside the VRChat folder and retreive the values.

But didn't wanted to obtain the userID myself without the user knowing, and so I haven't implemented that yet.
(I may add something like the dropdown in the OSC settings panel in the future)

- Point 2/3

Just a safety question, are you loading the OSC settings file with the button bellow?

![image](https://github.com/BlackStartx/VRC-Gesture-Manager/assets/26898122/ce2f8fb7-381e-45a9-bb6c-635c538aef01)

I'll wait your response before thinking about the related possibilities~

Thanks and sorry for the late reply~ ^-^ 🌺

**Comment by MistressPlague** [comment]
I tried both with and without loading them.

You could scan the folders for the blueprintId in the pipelinemanager; effectively doing discovery of which user.

I really would appreciate being able to load avatar saved config.

**Comment by MistressPlague** [comment]
The loading of config is enough of a need i'm attempting to make a addon cs file to do it; failing so far lol
![image](https://github.com/BlackStartx/VRC-Gesture-Manager/assets/36628963/18f3e898-d5cf-467f-9928-08f06a804834)

**Comment by MistressPlague** [comment]
I can't seem to find that simulation settings area, not matter where I go.

**Comment by MistressPlague** [comment]
Ohh, I see. Quite different to before lol.

**Comment by BlackStartx** [comment]
Touche, that was kinda an unusual place~ ^-^' 

Welp, glad you found it, hope that setting will do the trick~ 🌺

**Comment by MistressPlague** [comment]
Bug: Load stored parameters causing debug to not show the parameters due to an exception if there is config mismatch, such as something later removed.

To reproduce:
>have parameter with value in saved config
>have that parameter NOT be on the avatar
>brokey.

To fix:
Change ModuleVrc3.cs line 686 from:
foreach (var parameters in file.animationParameters) GetParam(parameters.name).InternalSet(parameters.value);
To
foreach (var parameters in file.animationParameters) GetParam(parameters.name)?.InternalSet(parameters.value);

**Comment by BlackStartx** [comment]
Hi Plague~ ^-^ 🌺 

Yeah, I can see that making sense~

I've considered to warn the user in case the JSON structure is not respected, but dunno why I haven't considered missmatched params that could crash the whole thinghie...

Thanks so much for the report, I may try to add this to the official 3.8.5 VCC release but it may be hard since I've already submitted it.
Otherwise this will be addressed in 3.8.6 for sure! :3 ✨ 

Thanks so much for the info~ ^-^

**Comment by MistressPlague** [comment]
You could do it as a minor hotfix, putting that ? into source, then editing the releases file(s).

**Comment by BlackStartx** [comment]
Smol update: I've pushed the fix, it's now live in the zip & unitypackage releases~ ^-^ 🌺

Once the VCC version will be approved the fix will also be included with the 3.8.5!
