### ISSUE TITLE
Add support for saving parameters between sessions

### ISSUE THREAD

**Issue by ShaunDreclin** [BlackStartx/VRC-Gesture-Manager#25]
Remembering all "saved" parameters would really help speed up my avatar testing, so I wouldn't have to re-set all the options in the radial menu every time. This one might need to be an option you can enable/disable, for people who prefer the current behaviour of automatically resetting everything.

**Comment by BlackStartx** [comment]
Hi Shaun~

Yeah, I will definetly add this in the newest version!
Hope it doesn't take too much~ 🌺 

- BlackStartx

**Comment by BlackStartx** [comment]
Welp... same here Shaun! :3

This is now official supported in the 3.8.5 version with a toggle in the new Settings Tab! 🌺 

Here is a sneak peek! :3

![image](https://github.com/BlackStartx/VRC-Gesture-Manager/assets/26898122/1b186ff5-d812-4f47-ba22-d500714c6937)

Right now it can only load parameters but not save them, hope it's good enough~
- BlackStartx
