### ISSUE TITLE
Set default avatar

### ISSUE THREAD

**Issue by fluffy-critter** [BlackStartx/VRC-Gesture-Manager#27]
In my scene I have four avatars (PC, PC fallback, Quest, Quest fallback), and I can't figure out the rhyme or reason to which one Gesture Manager decides to start up with when I activate it in play mode. I'd like to be able to select the one I'm actively working on from edit mode and have it stick. Is there any way to do this, or could that be added?

**Comment by BlackStartx** [comment]
Hi fluffy~ 🌺 

I've Pre-Relased the new 3.8.5 version of my Gesture Manager~ ^-^

I've added a brand new setting page, and in there you can now select a favourite avatar that the Gesture Manager would take control after entering Play-Mode!

![image](https://github.com/BlackStartx/VRC-Gesture-Manager/assets/26898122/43ff4d99-ce85-4820-ac33-539f032ec9e0)

This was not 100% the idea I had originally in mind, but I hope it's enough for creating a more predictable enviroment! :3

Hope that's good enough,
- BlackStartx

**Comment by fluffy-critter** [comment]
Ah, nice! That seems like it handles the issue I'd reported pretty nicely.

What happens if the one set as favorite isn't active at the time of activation? Would it be possible to set an array of fallbacks? That might be a bit nicer for one of the Easy Quest Switch use cases (i.e. having it always prioritize the main avatar over the fallback, when both main and fallback are activated in a build setting switch). But even just having one favorite slot is a *huge* improvement over how it used to be.

Thanks so much!
