### ISSUE TITLE
Debug Window Exceeds Width Of Inspector, Popout

### ISSUE THREAD

**Issue by MisutaaAsriel** [BlackStartx/VRC-Gesture-Manager#29]
# Issue
- On High DPI & Retina displays, the Debug window is improperly sized, exceeding the width of the inspector by more than double.
- Width is also double when popped out into a standalone window.
- 
# Cause
- `Screen.width` is being used instead of [`EditorGUIUtility.currentViewWidth`](https://docs.unity3d.com/2019.4/Documentation/ScriptReference/EditorGUIUtility-currentViewWidth.html) in [`ModuleVrc3`](https://github.com/BlackStartx/VRC-Gesture-Manager/blob/544895ec0f0b98e7901f85d21f6bb2fdc565e88d/Scripts/Editor/Modules/Vrc3/ModuleVrc3.cs#L433) & [`Vrc3AvatarDebugWindow.cs`](https://github.com/BlackStartx/VRC-Gesture-Manager/blob/544895ec0f0b98e7901f85d21f6bb2fdc565e88d/Scripts/Editor/Modules/Vrc3/Vrc3Debug/Avatar/Vrc3AvatarDebugWindow.cs#L51).
- On some systems, the number returned by `Screen.width` is a value much higher than the actual size on screen, due to the scale factor being higher than a factor of 1.0.
- `EditorGUIUtility.currentViewWidth` returns the current editor GUI width as rendered, rather than the raw, unscaled width.

# Environment
- MacBook Air M2
- 24GB RAM
- Unity 2019.4.31f
- Gesture Manager 3.8

**Comment by BlackStartx** [comment]
We have discussed this issue in the PR itself and it's now merged! ^-^
I'll close this issue as well!

Thanks again! :3 🌺
