### ISSUE TITLE
Blend Shapes Overshooting

### ISSUE THREAD

**Issue by TypicalZedF** [BlackStartx/VRC-Gesture-Manager#32]
![image](https://github.com/BlackStartx/VRC-Gesture-Manager/assets/82347194/3422513d-aec4-47ea-a233-736a91e77418)
In this photo, you can see when avatar testing, blend shapes REALLY overshot when they should only be maxing out at 100, this is the behavior in-game.

This broken look was achieved by already having the blend shapes set to 100 by default, and rather than the emulator considering that, it will basically add to the fire when it doesn't need to.

**Comment by BlackStartx** [comment]
Hi TypicalZed~ ^-^ 🌺

Thanks for the report, this is a knew problem but it can be easily solved by enabling the Unity setting under: 
`Player Settings -> Other Settings -> Legacy: Clamp BlendShapes`

![image](https://github.com/BlackStartx/VRC-Gesture-Manager/assets/26898122/7912c31e-acb4-499d-9659-13ab7a5a4819)

I always wanted to implement a way to help the user toggle that setting within the Gesture Manager itself, and finally with the new release that's in the process to be approved (v3.8.5) I have a place to put those options!

### Gesture Manager 3.8.5 Setting Window
![image](https://github.com/BlackStartx/VRC-Gesture-Manager/assets/26898122/f180b924-3702-48a8-9490-84a2468ece20)

This window will be accesible within the tool itself once the 3.8.5 officialy launch (It's currently in a pre-release state) meanwhile you can enable the setting manually! ^-^ ♥

Sorry for the issue, if you have any problem enabling the setting feel free to comment here!
- BlackStartx

**Comment by TypicalZedF** [comment]
Thank you for the information BlackStarx! Also thank you for such an amazing tool for avatar work. You're a lifesaver. 💖

**Comment by TypicalZedF** [comment]
Would it still be possible to allow a setting to turn this on when starting the project? maybe this is just me, but I've noticed slight changes when it comes to animating with Blendshapes now with the setting turned on.

**Comment by BlackStartx** [comment]
I would love to enable the setting once the tool gain control over an Avatar, but I saw that Editor settings seems to not reset upon leaving Play-Mode~

I could make hooks on start/end of Play-Mode, but those could sometimes not get called (due to crashes, assembly reloads, etc) and leaves the user with the toggle forever on. (which I don't like ;^;)
