### ISSUE TITLE
Errors on play

### ISSUE THREAD

**Issue by DaManUp** [BlackStartx/VRC-Gesture-Manager#34]
here are the errors I receive maybe its something I'm doing wrong.
#1
Packages\vrchat.blackstartx.gesture-manager\Scripts\Editor\Modules\Vrc3\DummyModes\Vrc3DummyMode.cs(28,24): error CS0234: The type or namespace name 'ExtensionMethods' does not exist in the namespace 'VRC.Core'
#2
Packages\vrchat.blackstartx.gesture-manager\Scripts\Editor\Modules\Vrc3\ModuleVrc3.cs(993,29): error CS1061: 'VRCPhysBoneBase' does not contain a definition for 'param_IsPosed' and no accessible extension method 'param_IsPosed' accepting a first argument of type 'VRCPhysBoneBase' could be found
#3 
Packages\vrchat.blackstartx.gesture-manager\Scripts\Editor\Modules\Vrc3\ModuleVrc3.cs(993,128): error CS0117: 'VRCPhysBoneBase' does not contain a definition for 'PARAM_ISPOSED'
#4
Packages\vrchat.blackstartx.gesture-manager\Scripts\Editor\Modules\Vrc3\ModuleVrc3.cs(995,29): error CS1061: 'VRCPhysBoneBase' does not contain a definition for 'param_Squish' and no accessible extension method 'param_Squish' accepting a first argument of type 'VRCPhysBoneBase' could be found
#5 
Packages\vrchat.blackstartx.gesture-manager\Scripts\Editor\Modules\Vrc3\ModuleVrc3.cs(995,127): error CS0117: 'VRCPhysBoneBase' does not contain a definition for 'PARAM_SQUISH'
Thank you for your time

**Comment by BlackStartx** [comment]
Hi DaMan~ ^-^

From the 5 errors you posted here it looks like you have an older SDK, one released prior than the [Squishy PhysBones](https://docs.vrchat.com/docs/vrchat-202322) update.
I would suggest (if this is the case) to updade the SDK~

If you have any other issues please feel free to comment and ask here!

P.S: The latest **3.4.0** version of the VRChat SDK does not have compatibilities issues with the latest release of Gesture Manager~

**Comment by BlackStartx** [comment]
I'll close this issue since there was no feedback for over two weeks, hope he solved the problem~ ^-^ 🌺
