### ISSUE TITLE
Contact Receivers set to "Allow Others" still get triggered in the Emulator

### ISSUE THREAD

**Issue by BluWizard10** [BlackStartx/VRC-Gesture-Manager#35]
There is one Avatar that I am using that has a Contact Sender and Contact Receiver targeting the same Bone (particularly the Head). They use a custom Tag and they are both sized the exact same, basically touching each other.

If they are both touching each other at the same time, the Contact will continuously trigger endlessly despite it being set to "Allow Others" only. Keep in mind that "Allow Self" is completely disabled on the Receiver.

Of course, this behavior is not possible in VRChat. However, it seems to happen in the Emulator only. Is this a bug or an intentional function of Gesture Manager?

**Comment by BlackStartx** [comment]
Hi Blu~ ^-^ 🌺 

This issue has been reported a year ago, once on issue #3 and then also on issue #5.

From what I remember, I had developed a solution to handle the two flags in the emulator, that solution should be almost fully indipendent from the SDK itself, but maybe in one year something changed and broke the behaviour (?)

I'm currently away from my workstation so I'm unable to test stuff, but once I'm back I'll give you more feedback~ ^-^

Sorry and thanks for the report~ ♥

###### P.S: This is probably not the case but I'll say it here anyway. <br> <br> I remember that the behaviour was working only for contacts that where placed before the initialization of the Avatar, meaning that if (somehow) you add a contact after the simulation has been initialized, than the two tags were ignored~

**Comment by BluWizard10** [comment]
> I remember that the behaviour was working only for contacts that where placed before the initialization of the Avatar, meaning that if (somehow) you add a contact after the simulation has been initialized, than the two tags were ignored~

Now that you mention this, VRCFury does it's own set of initializing the Avatar. So it's possible Gesture Manager caught that behavior and did something to cause it.

**Comment by BlackStartx** [comment]
Oh gosh, this is an old issue... anyway~

Gesture Manager 3.9.3 is around the corner and I've made some modification to handle this issue **way better**~
I'll notify it here just in case, since the new version will probably (if it was not already) fix this issue~ (Or at least it should (?))
