### ISSUE TITLE
3.8.8 not working in unity 2022

### ISSUE THREAD

**Issue by pigrass** [BlackStartx/VRC-Gesture-Manager#44]
hello, i tested gesture manager in unity 2022 and 2019
avatar is booth 3817645 as it is small size and easy

for unity 2022, i only imported 
resolver tool 0.1.27
base 3.5.0
avatar 3.5.0
liltoon1.6.0
![error](https://github.com/BlackStartx/VRC-Gesture-Manager/assets/51767950/fa012eca-282d-4447-b80d-94f1181d234c)
errors are all about unity
gesture emotions and expressions do not work

but in unity 2019, 3.8.8 works fine

please help fix it

**Comment by BlackStartx** [comment]
Hi Pigrass~ 🌺 

Sorry for the long time whitout a reply, by the way a common issue with 2022 is that Unity has an "**Error Pause**" feature enabled by default in the console.

I can also see that "**错误暂停**" is toggled on, and I think it may be the cause of the issue! ✨ 
May you check if your Editor is paused when you encoutered this issue?

Thanks and sorry once again,
- BlackStartx

**Comment by BlackStartx** [comment]
P.S: Un-checking "**错误暂停**" should solve the issue permanently after a Play-Mode restart! :3

**Comment by BlackStartx** [comment]
Super glad it helped! ^-^ 🌺 

And super sorry for the late reply~ :3
