### ISSUE TITLE
Gesture Manager toggles are not working

### ISSUE THREAD

**Issue by TechieUwU** [BlackStartx/VRC-Gesture-Manager#45]
I recently transferred my Unity file from version 2019 to version 2022, but now none of the toggles or expressions seem to work. I've updated the script and even reinstalled it, but still, nothing is working.

**Comment by BlackStartx** [comment]
Hi Techie~

There is a common issue related to the "Error Pause" option being toggled on in the 2022 console by default causing a lot of confusion between the users.

The side-effects are the same you're describing, may you check if that option is on in the Unity console? In case, toggling it off will probably solve the issue!

Thanks and sorry for the issue~ 🌸

**Comment by DS-ZaBoss** [comment]
Uncheaking "Error Pause" in the console seems to have fixed this issue for me.

**Comment by BlackStartx** [comment]
I'll close this issues since 3.8.9 is now officially downloadable from the VCC! :3

Now there will be a warning if the editor is paused!
