### ISSUE TITLE
Wrong behaviour for float/int -> bool mismatch

### ISSUE THREAD

**Issue by jellejurre** [BlackStartx/VRC-Gesture-Manager#49]
Wrong behaviour for float/int -> bool mismatch
Right now it's >0, it should be !=0
We fixed this up in the emulator and on the https://notes.sleightly.dev/parameter-mismatching/, so I thought I'd make an issue here as well

**Comment by BlackStartx** [comment]
Hi Jurre~ ^-^ 🌺 

Thanks so much for the info, I'm working on the 3.9.0 and I'll surely fix that in the new version!
At least I'm happy that the latest Unity 2019 version have this quirk *a little* fixed up~ ^-^ ✨ 

- BlackStartx

**Comment by BlackStartx** [comment]
I'll close the issues since 3.9.0 is now officially downloadable from the VCC~

And the fix has been implemented there~ :3
