### ISSUE TITLE
VRCAnimatorPlayAudio not working

### ISSUE THREAD

**Issue by Dennisonung** [BlackStartx/VRC-Gesture-Manager#50]
Recently the new VRCSDK update added the new state behavior `VRCAnimatorPlayAudio`, 
gesture manager doesn't do anything with this I'm pretty sure. Would be epic tho 👍

**Comment by BlackStartx** [comment]
Hi Dennisonung~

I've already finished developing the feature for the new `VRCAnimatorPlayAudio` and I will be shipping it really soon with a pre-release of the 3.9.0! ❤️

I'm currently just polishing things up so that I can publish the new version~ ^-^ ✨

**Comment by AraHaan** [comment]
> Hi Dennisonung~
> 
> I've already finished developing the feature for the new `VRCAnimatorPlayAudio` and I will be shipping it really soon with a pre-release of the 3.9.0! ❤️
> 
> I'm currently just polishing things up so that I can publish the new version~ ^-^ ✨

Can you please publish the pre-release in a few hours? I need to figure out why it does not play my clips at all in VRChat itself despite having the path to the AudioSource being correct and the clips being in the state behaviors of my animation controller for a toggle of mine. I wanted a random clip be selected to optimize the 1 out of 30 clips that it would randomly choose and sigificantly reduce my AudioSources from 30+ to 1. Ironically if I manually select one of the clip to be directly in the AudioSource it works properly in VRChat but is then stuck as that which is not what I wanted at all.

**Comment by BlackStartx** [comment]
Hi AraHaan~ 🌺 

The update is now live! :3
I saw your comment on the PR in the curated listing, so you may already be aware of that~

Anyway, I'll close the issues since 3.9.0 is now officially downloadable from the VCC~ 
Sorry for the long wait, and feel free to open anther issue (or re-open this one) if you're having issues! ♥

- BlackStartx
