### ISSUE TITLE
3.8.9 and 3.9.0 do not properly show AAP values in the parameter debugger

### ISSUE THREAD

**Issue by SenkyDragon** [BlackStartx/VRC-Gesture-Manager#53]
Create a new parameter in the fx controller, and give it a default value of 1, then start play mode. In 3.8.8, the parameter debugger properly shows the value is 1. In 3.8.9 and 3.9.0, it incorrectly says that the value is 0.

**Comment by BlackStartx** [comment]
Hey Senky, thanks so much for the info~ ♥

I've made a big change to how parameters are handled that caused some issues of miss-interpreted values.

I'll rework that part of the code to fix this and other related issues soon! ✨
