### ISSUE TITLE
Compression format suggestions for Quest avatars

### ISSUE THREAD

**Issue by kaikoga** [BlackStartx/VRC-Gesture-Manager#54]
I have run my Quest avatar through VRAM Calculator and noticed that compression format change from ASTC_4x4 to DXT1 is suggested.

I think we should stick to ASTC when we target Android devices.

![image](https://github.com/BlackStartx/VRC-Gesture-Manager/assets/4142423/f7c7c594-88ec-4b7f-ba71-ba0601a1cdfa)

**Comment by kaikoga** [comment]
Oops, wrong repository

**Comment by kaikoga** [comment]
By the way, I'm looking forward to VRCSDK 3.6.0-beta support of Gesture Manager!
Thank you!

**Comment by BlackStartx** [comment]
Hi Kaikoga~ ^-^ 🌺

About the **VRCSDK 3.6.0-beta**:

I've checked it out and the current Gesture Manager version (v3.9.0) does not have compilation issues~
I will bump up the compatibility on v3.9.1 so that the VCC won't trigger any warning! :3
