### ISSUE TITLE
Parameter drivers for triggers are not simulated.

### ISSUE THREAD

**Issue by JustBuddy** [BlackStartx/VRC-Gesture-Manager#56]
While working on an asset, I noticed that GM doesn't respond to parameter drivers driving parameters of the type trigger.
Those drivers are seemingly skipped. This works fine ingame, is just not emulated correctly.

![image](https://github.com/BlackStartx/VRC-Gesture-Manager/assets/8122264/a7a4b7bc-e631-403a-9f43-f4dc7d001ed7)

The parameter driver drives a trigger that does its thing on a different Layer, both are on the "Action" playable layer, if that matters.

Repro:
1. Create a trigger parameter
2. Create logic with a parameter driver that drives that trigger.
3. Trigger won't change in play-mode.

**Comment by BlackStartx** [comment]
Hi Buddy~ 🌺 
Thanks for the report!

I'll make sure to address this in the newest Gesture Manager's 3.9.2 release~ 👍🏻

**Comment by BlackStartx** [comment]
Hi Buddy~ :3 🌺 

I've released the new Gesture Manager 3.9.2 version that fixes this issue.
I've also started the curated listing process!

- BlackStartx
