### ISSUE TITLE
Avatar Descriptor contacts aren't evaluated

### ISSUE THREAD

**Issue by lackofbindings** [BlackStartx/VRC-Gesture-Manager#61]
The default contacts provided by the Avatar Descriptor (Head, Chest, Feet, etc.) don't seem to have any affect on contact receivers while the emulation is running.

SDK 3.7.1
Gesture Manager 3.9.2 VCC

**Comment by BlackStartx** [comment]
Hi @lackofbindings~ ^-^ 🌺

I'll make sure to address this feature in the upcoming versions!

Thanks for the feedback,
- BlackStartx

**Comment by BlackStartx** [comment]
Hey, I confirm I'll add this in Gesture Manager 3.9.3! ^-^

The new version is around the corner and it's currently in the testing phase~ :3 🌺

**Comment by BlackStartx** [comment]
The issue should now be resolved and the new version has been approved and is downloadable from the VCC! ✨ 

I'll close the issue, feel free to reopen it in case any errors occurs~ ^-^ 🌺
