### ISSUE TITLE
Error with VRCSDK3-AVATAR-2022.06.03.00.04_Public

### ISSUE THREAD

**Issue by unitynote** [BlackStartx/VRC-Gesture-Manager#9]
![image](https://user-images.githubusercontent.com/68238321/172937396-eb16aac4-6bdb-41fc-a238-5ec30d2f4c64.png)

**Comment by BlackStartx** [comment]
Hi UnityNote~

This may be the same as #8~

Please try to re-import the new SDK.
Once re-imported, if it still gives you error in console **CLOSE** and **OPEN** the Unity Project again.

Tell me if that fixes the issue~ ^-^ ♥
